name: Publish to npm

on: pull_request

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn --immutable
        # run: npm ci

      #   - name: Bootstrap Lerna
      #     run: npx lerna bootstrap
      - name: Publish to npm
        run: npx lerna publish --no-private --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
